repos:
  - repo: https://github.com/gitguardian/ggshield
    rev: v1.35.0
    hooks:
      - id: ggshield
        language_version: python3
        stages: [pre-commit]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: check-yaml
      - id: pretty-format-json
        args: [--no-ensure-ascii, --autofix]
        exclude: "tsconfig.json"

  - repo: https://github.com/bridgecrewio/checkov.git
    rev: 2.0.975
    hooks:
      - id: checkov

  - repo: https://github.com/Agilicus/pre-commit-hook-k8svalidate.git
    rev: v0.0.8
    hooks:
      - id: k8svalidate
        files: .yaml$
