services:
  frontend:
    image: sweportfoliosite_frontend:latest
    build:
      context: .
      dockerfile: src/front_end/Dockerfile
    ports:
      - "5173:5173"
    environment:
      NODE_ENV: development
      VITE_BACKEND_URL: ${BACKEND_URL}
      VITE_BACKEND_ROUTE: ${BACKEND_ROUTE}
      VITE_BACKEND_API_KEY: ${BACKEND_API_KEY}
      VITE_PAGE_VISIT_ROUTE_PATH: ${PAGE_VISIT_ROUTE_PATH}
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:5173"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    image: sweportfoliosite_backend:latest
    build:
      context: .
      dockerfile: src/back_end/Dockerfile
    ports:
      - "10000:10000"
    environment:
      RUST_LOG: debug
      PORT: 10000
      CORS_ORIGIN: ${CORS_ORIGIN}
      BACKEND_URL: ${BACKEND_URL}
      HEALTH_CHECK_URL_SUFFIX: ${HEALTH_CHECK_URL_SUFFIX}
      DATABASE_URL: ${DATABASE_URL}
      HOST_PLATFORM_ADDRESS: ${HOST_PLATFORM_ADDRESS}
      GITHUB_API_TOKEN: ${GITHUB_API_TOKEN}
      GITHUB_API_URL: ${GITHUB_API_URL}
      GITHUB_GRAPHQL_API_URL: ${GITHUB_GRAPHQL_API_URL}
      GITHUB_USERNAME: ${GITHUB_USERNAME}
      SUPABASE_PROJECT_ID: ${SUPABASE_PROJECT_ID}
      SUPABASE_DB_USER: ${SUPABASE_DB_USER}
      SUPABASE_DB_PASSWORD: ${SUPABASE_DB_PASSWORD}
      SUPABASE_PAGE_DB_NAME: ${SUPABASE_PAGE_DB_NAME}
      SUPABASE_DB_HOST: ${SUPABASE_DB_HOST}
      SUPABASE_DB_URL: ${SUPABASE_DB_URL}
      SUPABASE_DB_KEY: ${SUPABASE_DB_KEY}
    volumes:
      - app-data:/app/data
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:10000${HEALTH_CHECK_URL_SUFFIX}",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  app-data:
    driver: local

networks:
  app-network:
    driver: bridge
